"""empty message

Revision ID: 882d765f2737
Revises: 6c3c7ed6614e
Create Date: 2020-04-23 13:18:27.536754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882d765f2737'
down_revision = '6c3c7ed6614e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.drop_constraint('Shows_artist_id_fkey', 'Shows', type_='foreignkey')
    op.create_foreign_key(None, 'Shows', 'Venues', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'Shows', 'Artists', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.create_foreign_key('Shows_artist_id_fkey', 'Shows', 'Venues', ['artist_id'], ['id'])
    op.drop_column('Shows', 'venue_id')
    # ### end Alembic commands ###
